ARG RELEASE=1.19.5-202312290818

FROM yylt/proxyv2:${RELEASE}

ENV SIDECAR=envoy
# Install Envoy.
COPY ./${SIDECAR} /usr/local/bin/${SIDECAR}
COPY ./${SIDECAR} /usr/local/${SIDECAR}
COPY ./bazel-bin/${SIDECAR} /usr/local/bin/${SIDECAR}
COPY ./bazel-bin/${SIDECAR} /usr/local/${SIDECAR}
RUN chmod 0755 /usr/local/bin/${SIDECAR}
