ARG RELEASE=1.19.5-202312290818

FROM yylt/proxyv2:${RELEASE}

# Install Envoy.
COPY linux_amd64/envoy /usr/local/bin/envoy
COPY linux_amd64/envoy /usr/local/envoy
RUN chmod 0755 /usr/local/bin/envoy
